### ISSUE TITLE
Can not have enough instances 

### ISSUE THREAD

**Issue by HaochenQ** [Azure/Event-Hubs-extension-for-Azure-Functions#112]
Hi Team,

We have around 100 event hubs partitions and are using a Premium Function plan, however, the maximum instance we can get is only 15 which is affecting the performance.

Is there any configuration within [azure-functions-eventhubs-extension] we can make to use more instances?

We are migrating from Sevice Bus for the costing reason while the performance on Service bus is much better.

Extension in use: 5.0.0-beta.6 

host.json:
{
  "version": "2.0",
  "aggregator": {
    "batchSize": 1000,
    "flushTimeout": "00:00:05"
  },
  "healthMonitor": {
    "enabled": true,
    "healthCheckInterval": "00:00:10",
    "healthCheckWindow": "00:02:00",
    "healthCheckThreshold": 6,
    "counterThreshold": 0.8
  },
  "extensions": {
    "eventHubs": {
      "eventProcessorOptions": {
        "maxBatchSize": 128,
        "prefetchCount": 512
      },
      "initialOffsetOptions": {
        "type": "fromEnqueuedTime",
        "enqueuedTimeUtc": "2022-05-25T18:00:00Z"
      }
    }
  }
}

Many thanks!

**Comment by alrod** [comment]
@[HaochenQ](https://github.com/HaochenQ), can you please [privately share](https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately) you function app name and a timestamp when you have "the maximum instance we can get is only 15 which is affecting the performance"
